services:
  funasr:
    image: registry.cn-hangzhou.aliyuncs.com/funasr_repo/funasr:funasr-runtime-sdk-online-cpu-0.1.13
    container_name: funasr-asr
    ports:
      - "10095:10095"
    volumes:
      - ./models:/workspace/models
    working_dir: /workspace/FunASR/runtime
    restart: unless-stopped
    command: >
      bash -c "
      bash run_server_2pass.sh
        --download-model-dir /workspace/models
        --model-dir iic/SenseVoiceSmall-onnx
        --online-model-dir damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online-onnx
        --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-onnx
        --punc-dir damo/punc_ct-transformer_zh-cn-common-vad_realtime-vocab272727-onnx
        --port 10095
      "
