services:
  funasr:
    image: registry.cn-hangzhou.aliyuncs.com/funasr_repo/funasr:funasr-runtime-sdk-online-cpu-0.1.13
    container_name: funasr-asr
    ports:
      - "10095:10095"
    volumes:
      - ./models:/workspace/models
    working_dir: /workspace/FunASR/runtime
    restart: unless-stopped
    command: bash run_server.sh --download-model-dir /workspace/models --certfile 0 --port 10095
